Downgrade to Ubuntu 22.04 due to build failure on 24.04
Ubuntu 24.04 is incompatible with contourpy, which uses Meson with the
Python backend. The build fails with a missing header:

  |                  from ../contourpy-1.2.1/src/base_impl.h:4,
  |                  from ../contourpy-1.2.1/src/wrap.cpp:1:
  | /usr/include/python3.12/pyconfig.h:9:12: fatal error: aarch64-linux-gnu/python3.12/pyconfig.h: No such file or directory
  |     9 | #  include <aarch64-linux-gnu/python3.12/pyconfig.h>
  |       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | cc1plus: all warnings being treated as errors
  | compilation terminated.

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>